config/routes.rb
Site::Application.routes.draw do
  resources :artigos
  root :to => 'artigos#index'

end

app/models/artigo.rb
class Artigo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artigos_controller.rb
class ArtigosController < ApplicationController
  # GET /artigos
  # GET /artigos.json
  
  layout "artigo"
  
  def index
    @artigos = Artigo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artigos }
    end
  end

  # GET /artigos/1
  # GET /artigos/1.json
  def show
    @artigo = Artigo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artigo }
    end
  end

  # GET /artigos/new
  # GET /artigos/new.json
  def new
    @artigo = Artigo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artigo }
    end
  end

  # GET /artigos/1/edit
  def edit
    @artigo = Artigo.find(params[:id])
  end

  # POST /artigos
  # POST /artigos.json
  def create
    @artigo = Artigo.new(params[:artigo])

    respond_to do |format|
      if @artigo.save
        format.html { redirect_to @artigo, notice: 'Artigo was successfully created.' }
        format.json { render json: @artigo, status: :created, location: @artigo }
      else
        format.html { render action: "new" }
        format.json { render json: @artigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artigos/1
  # PUT /artigos/1.json
  def update
    @artigo = Artigo.find(params[:id])

    respond_to do |format|
      if @artigo.update_attributes(params[:artigo])
        format.html { redirect_to @artigo, notice: 'Artigo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artigos/1
  # DELETE /artigos/1.json
  def destroy
    @artigo = Artigo.find(params[:id])
    @artigo.destroy

    respond_to do |format|
      format.html { redirect_to artigos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/views/artigos/_form.html.haml
= form_for(@artigo) do |f|
	-if @artigo.errors.any?
		%div{:id => "error_explanation"}
			%h2
				= pluralize(@artigo.errors.count, "error")
				prohibited this artigo from being saved:
			%ul
				- @artigo.errors.full_messages.each do |msg|
					%li
						= msg

	%div{:class=>"field"}
		= f.label :titulo
		%br
		= f.text_field :titulo

	%div{:class=>"field"}
		= f.label :data
		%br
		= f.date_select(:data, :order => [:day, :month, :year], :start_year => 1900, :end_year => 2100, :use_month_names => %w(Janeiro Fevereiro Março Abril Maio Junho Julho Agosto Setembro Outubro Novembro Dezembro) )

	%div{:class=>"field"}
		= f.label :texto
		%br
		= f.text_area :texto

	%div{:class=>"actions"}
		= image_submit_tag("gravar.png")
		= link_to image_tag("voltar.png", :size => "128x64" ), artigos_path

app/views/artigos/edit.html.haml
%h1 Editando artigo
= render 'form'

app/views/artigos/index.html.haml
%h1 Listando Artigos

%table
	%tr
		%th Título
		%th Data
		%th Consultar
		%th Alterar
		%th Excluir

	-tamIco = "30x30" # tamanho dos icones
  
	-@artigos.each do |artigo|
		%tr
			%td
				=artigo.titulo
			%td 
				=artigo.data.strftime("%d/%m/%Y")
			%td 
				=link_to image_tag("icone_consultar.gif", :size => tamIco ), artigo
			%td 
				=link_to image_tag("icone_alterar.png", :size => tamIco ), edit_artigo_path(artigo)
			%td 
				=link_to image_tag("icone_excluir.gif", :size => tamIco ), artigo, confirm: 'Deseja excluir este Registro? ' +artigo.titulo, method: :delete
%br
= link_to image_tag("novo.png", :size => "150x54" ), new_artigo_path

app/views/artigos/new.html.haml
%h1 Novo Artigo
= render 'form'

app/views/artigos/show.html.haml
%h1 Consultando Artigo

-cab = ["Título","Data","Texto"]
-campos = ["titulo","data","texto"]

%table{:class => "show"}
	-for ct in (0..2)
		%tr
			%td{:class => "cab"} 
				= cab[ct] + ":"
			- if campos[ct] == "data"
				%td
					= @artigo[campos[ct]].strftime("%d/%m/%Y")
			- else
				%td
					= simple_format @artigo[campos[ct]]

= link_to image_tag("voltar.png", :size => "128x64" ), artigos_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Site</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/artigo.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta name="keywords" content="" />
		<meta name="description" content="" />
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>Site Treinamento Padawan</title>
		
		<%= javascript_include_tag "application" %>
		<%= stylesheet_link_tag "styleArtigo", :media => "all" %> <!-- Chamando CSS -->
		<%= csrf_meta_tags %>
		
	</head>
	<body>
		<div id="container">
			<div id="header">
			</div>	

			<div id="nav">
				<%= image_tag("logo.png", :class => "logo" ) %>
			</div>	
			
			<div id="content">
				<%= yield %>
			</div>	
			
		</div>	
	</body>
</html>